spring:
  application:
    name: project-management-api-spring
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/project_management_spring}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true